version: "2"

services:
  app:
    image: golang:1.11.2 
    volumes:
      - .:/go/src/cart
    working_dir: /go/src/cart
    command: go run main.go
    links:
      - shopping_cart
    depends_on:
      - shopping_cart
    ports:
      - 8080:8080

  shopping_cart:
    image: mysql:5.7
    volumes: 
      - ./mysql/data/dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shopping_cart
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks: 
      - default
    ports: 
      - 3306:3306
    
      
    
    




  
    